In [16]:
from sklearn.datasets import load_diabetes
from sklearn.metrics import mean_squared_error
import numpy as np
diabetes = load_diabetes()
diabetes

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
        128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
        150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
        200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
         42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
         83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
        104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
        173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
        107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
         60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
        197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
         59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
        237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
        143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
        142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
         77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
         78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
        154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
         71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
        150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
        145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
         94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
         60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
         31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
        114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
        191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
        244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
        263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
         77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
         58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
        140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
        219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
         43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
        140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
         84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
         94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
        220.,  57.]),
 'frame': None,
 'DESCR': '.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n  :Number of Instances: 442\n\n  :Number of Attributes: First 10 columns are numeric predictive values\n\n  :Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n  :Attribute Information:\n      - age     age in years\n      - sex\n      - bmi     body mass index\n      - bp      average blood pressure\n      - s1      tc, total serum cholesterol\n      - s2      ldl, low-density lipoproteins\n      - s3      hdl, high-density lipoproteins\n      - s4      tch, total cholesterol / HDL\n      - s5      ltg, possibly log of serum triglycerides level\n      - s6      glu, blood sugar level\n\nNote: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).\n\nSource URL:\nhttps://www4.stat.ncsu.edu/~boos/var.select/diabetes.html\n\nFor more information see:\nBradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.\n(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)\n',
 'feature_names': ['age',
  'sex',
  'bmi',
  'bp',
  's1',
  's2',
  's3',
  's4',
  's5',
  's6'],
 'data_filename': 'diabetes_data_raw.csv.gz',
 'target_filename': 'diabetes_target.csv.gz',
 'data_module': 'sklearn.datasets.data'}

In [7]:
import pandas as pd
pd.DataFrame(diabetes.data, columns=("age", "sex", "bmi", "map", "s1", "s2", "s3", "s4", "s5", "s6"))

,age,sex,bmi,map,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [8]:
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(diabetes.data, diabetes.target, random_state=42)

In [9]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(train_X, train_y)
print(model.score(test_X, test_y))
print(model.predict(test_X))

0.4849058889476755
[137.94908878 182.533354   129.85295373 292.5630923  124.86788221
  89.73883143 255.95872903 177.64545905  87.8884795  107.93961905
  93.26357149 171.11939483  56.06305218 207.22146277  99.78918734
 131.7128101  215.86378125 252.18591603 201.56577486 220.38870357
 204.35745939  88.9068622   68.52958146 190.02378425 153.91270751
 164.02719031 192.83227597 187.16765226  46.60570802 109.3112624
 175.04965912  87.8076198  130.37646375 186.56325253 172.4733248
 188.61448165 124.07175323 119.16132637 147.74400127  59.27254049
  70.90046253 109.30036497 170.97191153 156.56943489 168.68664924
  61.5457612   71.19039454 111.94779801  54.32009551 165.81267886
 152.78043565  63.80587155 110.07651605 108.64317139 179.16381014
 156.79651896  93.29011121 212.91986757 119.28417849  70.70890653
 186.678156   205.65720098 140.02890626 106.54792751 131.56053828
 204.1777152  173.28530628 168.65451177 123.58356159 145.48705122
 182.55320386 200.92667653 234.12723658 148.64994751  82.27100531
 162.11044268 191.41240355 208.42456254 159.81231419 207.08218272
 108.51881567 141.86853307  51.88969227  52.84070977 114.22596758
  77.8342828   82.21344298  56.82131329 167.18495845 188.01895568
 153.37024514 242.28645379 108.00439128  63.19252263  55.14671457
 197.58282031 248.94925646 184.2773709  104.76270243  63.45726497
 196.41780688 110.05014478 296.72299518  98.13799734 151.08901065
 105.09659013 131.61057546 128.29545093 166.00077036 185.58746376
 111.88655248]

In [10]:
print(model.score(test_X, test_y))

0.4849058889476755

In [11]:
print(model.score(train_X, train_y))

0.519034189167905

In [12]:
pred_y=model.predict(test_X)

In [15]:
(pred_y-test_y)**2

array([6.56925021e+03, 1.26637558e+04, 5.20519629e+03, 3.91414052e+03,
       1.92318157e+02, 3.29341862e+01, 1.94846116e+02, 8.90277940e+03,
       3.73506828e+01, 1.42554503e+02, 5.42326951e-01, 6.54167229e+03,
       1.84358149e+03, 8.06018575e+03, 1.23980133e+03, 4.18774779e+03,
       6.26254112e+03, 1.39572580e+02, 9.96398143e+02, 2.98239370e+03,
       1.11603464e+04, 6.20351785e+02, 3.53673068e+03, 1.76200269e+03,
       6.20642996e+02, 2.11850225e+03, 4.92350950e+03, 1.21369116e+04,
       1.94405013e+00, 5.34193388e+00, 1.22847860e+03, 6.34656020e+02,
       1.63025883e+03, 5.09100365e+02, 5.66508396e+01, 1.97007424e+03,
       6.73577268e+03, 1.23631887e+03, 5.88353474e+02, 1.38939544e+01,
       5.24431184e+02, 1.69094906e+00, 2.24158135e+02, 1.30657819e+02,
       6.19158877e+03, 9.11215568e+01, 1.65919145e+04, 6.22392626e+02,
       1.27305558e+03, 8.49850218e+03, 2.81583021e+02, 8.87253384e+03,
       1.68728017e+03, 1.34272201e+03, 6.66477960e+01, 3.81880976e+03,
       4.53268836e+02, 3.83407000e+03, 2.37323127e+03, 1.14680679e+02,
       4.18326386e+03, 2.36105354e+04, 2.20628365e+03, 2.06836446e+01,
       6.79626485e+03, 1.92039265e+03, 5.95164992e+01, 3.44035175e+03,
       2.69499450e+02, 3.19371338e+03, 6.65092506e+03, 4.44084962e+02,
       2.19705595e+03, 7.68251330e+03, 4.52793696e+01, 5.05669506e+03,
       2.92941122e+01, 1.33990752e+02, 5.95793884e+03, 6.71733253e+02,
       1.64177442e+03, 2.31663811e+03, 1.94571925e+03, 3.67078402e+02,
       1.50342559e+03, 4.06656150e+02, 2.04425543e+03, 3.81761694e+01,
       2.82745622e+02, 1.93766846e+03, 1.13585523e+01, 1.42231157e+03,
       2.88850716e+02, 1.75772460e+01, 9.70872338e+01, 6.95842587e+03,
       7.86844213e+02, 2.98507545e+02, 2.17937383e+02, 7.29783217e+01,
       3.39215610e+02, 4.86208885e+02, 7.14118472e+02, 8.19105922e+00,
       2.10781894e+03, 6.55547718e+01, 6.17962257e+03, 3.28276870e+03,
       9.21585209e+03, 1.78456105e+04, 9.77439200e+01])

In [21]:
mse = mean_squared_error(test_y, pred_y)
print(np.sqrt(mse))#平均二乗誤差

53.369566710321955

In [26]:
mse = np.mean((test_y-pred_y)**2)
print(mse)

2848.3106508475057

In [25]:
mae = np.mean(np.abs(test_y-pred_y))
print(mae)

41.54850685988061

In [27]:
pred_y=model.predict(train_X)
mse = np.mean((train_y-pred_y)**2)
print(mse)#平均二乗誤差
mae = np.mean(np.abs(train_y-pred_y))
print(mae)

2907.2577640101085
44.054803735772055